### ISSUE TITLE
Is this repo deprecated?

### ISSUE THREAD

**Issue by XuHuaiyu** [slimsag/rand#1]
I found this repo from `https://godoc.org/github.com/slimsag/rand/simd`.
But it seems this repo is deprecated now?

**Comment by slimsag** [comment]
It is very funny to me that you ask this :)

GitHub repository description:

> Random useless/WIP source code.

GitHub repository README:

> Random useless/WIP source code.
>
> Please don't use it; most of it is severly broken and 2+ years old.
>
> Eventually I will delete this repo entirely, but it does have some useful stuff hidden around.
